### ISSUE TITLE
[doc] Clarify in readme: Handling of template literals aka multi-line strings

### ISSUE THREAD

**Issue by mk-pmb** [chgibb/NwSJS#13]
I searched the readme for "multi" and "template" but found none. Could you clarify what kinds of whitespace in them is preserved, using both keywords?

**Comment by chgibb** [comment]
Feel free to open a PR. Template strings are handled correctly.

**Comment by mk-pmb** [comment]
Does "correctly" mean they're copied verbatim?

**Comment by chgibb** [comment]
Correct.
