### ISSUE TITLE
Fails to run on Ubuntu trusty

### ISSUE THREAD

**Issue by mk-pmb** [chgibb/NwSJS#14]
```text
$ ./nwsjs
bash: ./nwsjs: cannot execute binary file: Exec format error
$ sha1sum -b nwsjs
10ff7cdc56475025f81334c39bc39005d046864d *nwsjs
$ file nwsjs | fmt
nwsjs: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV),
dynamically linked (uses shared libs), for GNU/Linux 2.6.32,
BuildID[sha1]=5cc39dc67a6e046b2db450862f373f16a3f14ff7, stripped
$ node-versions
Node.js v6.11.0, npm v4.4.0, Ubuntu 14.04.5 LTS trusty,
kernel: 3.13.0-119-generic, machine/CPU/platform: i686 i686 i686
```

**Comment by chgibb** [comment]
I saw the same issues in the past. The Linux executable is built on Travis CI running Ubuntu Precise. Alas I am not sure how to resolve this.

**Comment by mk-pmb** [comment]
Would you migrate the package to JavaScript if someone were to translate the algorithm?

**Comment by chgibb** [comment]
I wrote this utility some time ago as ```uglifyjs``` did not yet support ES6. I've personally migrated away from using this in favour of [uglifyes](https://www.npmjs.com/package/uglify-es) which has so far supported all the ES6 features that I've had need of.

**Comment by mk-pmb** [comment]
Thanks! Then I'll just use that instead, too.
